import type { Bead, Material, ResonanceTag } from "@/lib/types";

export const BEADS: Bead[] = [
  {
    slug: "gold-sheen-obsidian",
    name: "金曜石手串",
    westernName: "Gold Sheen Obsidian",
    resonance: ["Wealth", "Career"],
    material: "Obsidian",
    description:
      "Volcanic glass veiled in a drifting golden shimmer. Worn by those who move toward ambition without losing themselves — it is said to reveal the truest path to abundance while dissolving the noise of doubt.",
    color: "#B8923A",
    price: 168,
    image: "/beads/gold-sheen-obsidian.jpg",
    origin: "Jalisco, Mexico — born of cooled volcanic flow",
    age: "≈ 10,000 years · Holocene volcanic glass",
    energyAlignment: "Solar Plexus · the seat of will and prosperity",
    diameterMm: 10,
  },
  {
    slug: "rutilated-quartz",
    name: "金发晶手串",
    westernName: "Rutilated Quartz",
    resonance: ["Wealth"],
    material: "Quartz",
    description:
      "Clear quartz threaded with filaments of golden rutile, like captured sunlight. An amplifier of intention, it lends momentum to the wearer's pursuits and is treasured as the stone of illuminated focus.",
    color: "#D4AF37",
    price: 214,
    image: "/beads/rutilated-quartz.jpg",
    origin: "Minas Gerais, Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Crown · clarity threaded with golden drive",
    diameterMm: 8,
  },
  {
    slug: "nephrite-jade",
    name: "和田玉手串",
    westernName: "Nephrite Jade",
    resonance: ["Peace", "Health"],
    material: "Jade",
    description:
      "The imperial stone of the East, cool and luminous. For millennia a talisman of harmony and quiet prosperity, jade is worn close to the skin to temper the spirit and invite enduring good fortune.",
    color: "#7FA07A",
    price: 240,
    image: "/beads/nephrite-jade.jpg",
    origin: "Hetian, Xinjiang",
    age: "≈ 250 million years · Paleozoic metamorphism",
    energyAlignment: "Heart · balance, mercy and abundance",
    diameterMm: 12,
  },
  {
    slug: "amethyst",
    name: "紫水晶手串",
    westernName: "Amethyst",
    resonance: ["Wealth", "Career", "Sleep", "Relationships", "Study"],
    material: "Quartz",
    description:
      "A violet hush rendered in stone. Long the companion of the contemplative, amethyst stills the restless mind and draws a protective calm around the wearer — clarity arrived at through stillness.",
    color: "#9B7BB8",
    price: 152,
    image: "/beads/amethyst.jpg",
    origin: "Uruguay — deep-vug cathedral geodes",
    age: "≈ 130 million years · Cretaceous basalt",
    energyAlignment: "Third Eye · intuition and serene insight",
    diameterMm: 10,
  },
  {
    slug: "clear-quartz",
    name: "白水晶手串",
    westernName: "Clear Quartz",
    resonance: ["Health", "Study"],
    material: "Quartz",
    description:
      "The master stone — flawless, transparent, infinitely receptive. It takes the wearer's intention and returns it magnified. A blank score upon which any resonance may be composed.",
    color: "#E8E6E1",
    price: 128,
    image: "/beads/clear-quartz.jpg",
    origin: "Arkansas, United States",
    age: "≈ 300 million years · Paleozoic",
    energyAlignment: "All centers · pure amplification",
    diameterMm: 10,
  },
  {
    slug: "black-obsidian",
    name: "黑曜石手串",
    westernName: "Black Obsidian",
    resonance: ["Peace"],
    material: "Obsidian",
    description:
      "A mirror of the deep, polished to liquid darkness. The guardian stone — it forms a quiet shield against discord and returns the wearer, again and again, to solid ground.",
    color: "#1B1B1F",
    price: 138,
    image: "/beads/black-obsidian.jpg",
    origin: "Armenia — Pleistocene obsidian fields",
    age: "≈ 2 million years · Pleistocene volcanic glass",
    energyAlignment: "Root · grounding and the dissolving of fear",
    diameterMm: 10,
  },
  {
    slug: "citrine",
    name: "黄水晶手串",
    westernName: "Citrine",
    resonance: ["Wealth", "Study"],
    material: "Quartz",
    description:
      "Sunlight crystallized into honeyed gold. The merchant's stone, said never to hold negativity — it invites warmth, generosity and the easy circulation of fortune through the wearer's life.",
    color: "#C99A2E",
    price: 176,
    image: "/beads/citrine.jpg",
    origin: "Rio Grande do Sul, Brazil",
    age: "≈ 130 million years · Cretaceous basalt",
    energyAlignment: "Solar Plexus · radiant prosperity",
    diameterMm: 8,
  },
  {
    slug: "smoky-quartz",
    name: "茶晶手串",
    westernName: "Smoky Quartz",
    resonance: ["Health", "Sleep"],
    material: "Quartz",
    description:
      "Quartz steeped in a soft, smoke-grey depth. A stone of restoration, it draws off the weight of the day and returns vitality — grounding without dimming the wearer's light.",
    color: "#5A4D45",
    price: 144,
    image: "/beads/smoky-quartz.jpg",
    origin: "Cairngorm Mountains, Scotland",
    age: "≈ 400 million years · Devonian granite",
    energyAlignment: "Root · renewal and steady vitality",
    diameterMm: 10,
  },
  {
    slug: "red-agate",
    name: "红玛瑙手串",
    westernName: "Red Agate",
    resonance: ["Health"],
    material: "Agate",
    description:
      "A stone of deep crimson warmth — red agate carries the energy of vitality and courage. Worn as a shield against negativity, it fortifies the spirit and restores confidence in moments of doubt.",
    color: "#B03030",
    price: 136,
    image: "/beads/red-agate.jpg",
    origin: "Yunnan, China",
    age: "≈ 100 million years · Cretaceous volcanic",
    energyAlignment: "Root · courage and vital protection",
    diameterMm: 8,
  },
  {
    slug: "black-hair-crystal",
    name: "黑发晶手串",
    westernName: "Black Tourmalinated Quartz",
    resonance: ["Career"],
    material: "Quartz",
    description:
      "Clear quartz laced with threads of black tourmaline — a stone of both clarity and shielding. It purifies the energetic field while grounding scattered thoughts, a dual gift of protection and light.",
    color: "#2A2A35",
    price: 198,
    image: "/beads/black-hair-crystal.jpg",
    origin: "Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Root & Crown · purifying clarity",
    diameterMm: 8,
  },
  {
    slug: "rose-quartz",
    name: "粉水晶手串",
    westernName: "Rose Quartz",
    resonance: ["Relationships", "Emotion"],
    material: "Quartz",
    description:
      "The stone of unconditional love — soft, rose-blush and gentle. It opens the heart to receive and give with equal ease, dissolving old wounds and inviting tender connection into the wearer's life.",
    color: "#E8B4C0",
    price: 142,
    image: "/beads/rose-quartz.jpg",
    origin: "Madagascar",
    age: "≈ 550 million years · Precambrian",
    energyAlignment: "Heart · love and gentle healing",
    diameterMm: 10,
  },
  {
    slug: "tiger-eye",
    name: "虎眼石手串",
    westernName: "Tiger Eye",
    resonance: ["Peace"],
    material: "Quartz",
    description:
      "Golden bands of silk move beneath the surface like a living flame — tiger eye carries the boldness of the hunter and the patience of the observer. A stone for those who seek prosperity through decisive action.",
    color: "#B87333",
    price: 158,
    image: "/beads/tiger-eye.jpg",
    origin: "Northern Cape, South Africa",
    age: "≈ 2.6 billion years · Archean ironstone",
    energyAlignment: "Solar Plexus · bold prosperity",
    diameterMm: 10,
  },
  {
    slug: "lapis-lazuli",
    name: "青金石手串",
    westernName: "Lapis Lazuli",
    resonance: ["Peace"],
    material: "Lapis Lazuli",
    description:
      "Night sky compressed into stone — deep indigo flecked with gold pyrite. Revered for millennia as a stone of wisdom and truth, lapis opens the mind to higher understanding and grants the clarity to speak one's truth.",
    color: "#1F4080",
    price: 226,
    image: "/beads/lapis-lazuli.jpg",
    origin: "Badakhshan, Afghanistan",
    age: "≈ 600 million years · Precambrian marble",
    energyAlignment: "Third Eye & Throat · wisdom and truth",
    diameterMm: 12,
  },

  // ── New stones from the resonance chart ──────────────────────────────────────
  {
    slug: "green-phantom",
    name: "绿幽灵手串",
    westernName: "Green Phantom Quartz",
    resonance: ["Wealth"],
    material: "Quartz",
    description:
      "Clear quartz holding a pyramid of green chlorite suspended within, like a forest sealed in glass. The classic stone of earned wealth — it is said to draw steady, honest prosperity and the patience to let it grow.",
    color: "#4A6B4E",
    price: 198,
    image: "/beads/green-phantom.jpg",
    origin: "Minas Gerais, Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Heart · the slow accumulation of fortune",
    diameterMm: 10,
  },
  {
    slug: "garnet",
    name: "石榴石手串",
    westernName: "Garnet",
    resonance: ["Health"],
    material: "Garnet",
    description:
      "Deep wine-red crystal with the glow of a held ember. A stone of circulation and vitality, garnet is worn to warm the body's energy, restore stamina and rekindle the wearer's appetite for life.",
    color: "#7B1E2B",
    price: 156,
    image: "/beads/garnet.jpg",
    origin: "Rajasthan, India",
    age: "≈ 1 billion years · Proterozoic schist",
    energyAlignment: "Root · vitality and the warmth of blood",
    diameterMm: 8,
  },
  {
    slug: "red-rabbit-hair",
    name: "红胶花手串",
    westernName: "Red Rabbit-Hair Quartz",
    resonance: ["Health"],
    material: "Quartz",
    description:
      "Clear quartz shot through with fine crimson hematite needles, soft as spun thread. A gentle, feminine stone of vitality — it is said to nourish the blood, lift the spirits and restore a healthy glow.",
    color: "#B5544E",
    price: 184,
    image: "/beads/red-rabbit-hair.jpg",
    origin: "Minas Gerais, Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Sacral · warmth, vitality and renewal",
    diameterMm: 8,
  },
  {
    slug: "black-gold-super-seven",
    name: "黑金超七手串",
    westernName: "Black Gold Super Seven",
    resonance: ["Career"],
    material: "Super Seven",
    description:
      "A union of seven minerals in one dark, gold-glinting stone. Long held as a talisman of authority and momentum, it is worn to steady ambition, sharpen resolve and carry the wearer forward in their work.",
    color: "#2B2620",
    price: 268,
    image: "/beads/black-gold-super-seven.jpg",
    origin: "Espírito Santo, Brazil",
    age: "≈ 500 million years · Precambrian",
    energyAlignment: "Root & Crown · grounded, driven ascent",
    diameterMm: 10,
  },
  {
    slug: "green-rabbit-hair",
    name: "绿兔毛手串",
    westernName: "Green Rabbit-Hair Quartz",
    resonance: ["Career"],
    material: "Quartz",
    description:
      "Clear quartz filled with silky green actinolite fibres, like meadow grass caught in ice. A stone of opportunity and growth, it is said to open doors in one's work and quicken the path to advancement.",
    color: "#6E7B3F",
    price: 188,
    image: "/beads/green-rabbit-hair.jpg",
    origin: "Minas Gerais, Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Heart · momentum and flourishing work",
    diameterMm: 8,
  },
  {
    slug: "moonstone",
    name: "月光石手串",
    westernName: "Moonstone",
    resonance: ["Sleep", "Emotion"],
    material: "Feldspar",
    description:
      "A milky stone that floats a blue light across its surface as it turns, like moonrise on water. Worn for calm and gentle dreaming, it softens the tides of feeling and brings rest to a restless heart.",
    color: "#D7E0EA",
    price: 172,
    image: "/beads/moonstone.jpg",
    origin: "Sri Lanka",
    age: "≈ 550 million years · Precambrian gneiss",
    energyAlignment: "Crown · lunar calm and intuition",
    diameterMm: 10,
  },
  {
    slug: "prehnite",
    name: "葡萄石手串",
    westernName: "Prehnite",
    resonance: ["Sleep"],
    material: "Prehnite",
    description:
      "A translucent stone of pale grape-green, luminous as early spring. Known as a stone of peace, it quiets an overactive mind, eases the body toward rest and invites untroubled, restorative sleep.",
    color: "#A7C796",
    price: 164,
    image: "/beads/prehnite.jpg",
    origin: "Kayes Region, Mali",
    age: "≈ 200 million years · Mesozoic basalt",
    energyAlignment: "Heart · unburdening and deep rest",
    diameterMm: 10,
  },
  {
    slug: "grey-agate",
    name: "灰玛瑙手串",
    westernName: "Grey Agate",
    resonance: ["Sleep"],
    material: "Agate",
    description:
      "Soft concentric bands of smoke and ash, cool and unhurried. A grounding, balancing stone, grey agate settles a scattered nervous system and draws the wearer down into a slow, steady, restful stillness.",
    color: "#6E6A66",
    price: 132,
    image: "/beads/grey-agate.jpg",
    origin: "Inner Mongolia, China",
    age: "≈ 100 million years · Cretaceous volcanic",
    energyAlignment: "Root · stillness and quiet balance",
    diameterMm: 10,
  },
  {
    slug: "cinnabar",
    name: "朱砂手串",
    westernName: "Cinnabar",
    resonance: ["Peace"],
    material: "Cinnabar",
    description:
      "A vivid, sacred vermilion long used across the East to ward and to bless. Cinnabar is worn as a guardian against ill fortune — a stone of protection and peace that keeps the wearer safe upon every road.",
    color: "#9C2A24",
    price: 208,
    image: "/beads/cinnabar.jpg",
    origin: "Guizhou, China",
    age: "≈ 60 million years · Cenozoic hydrothermal",
    energyAlignment: "Root · protection and auspicious calm",
    diameterMm: 10,
  },
  {
    slug: "kunzite",
    name: "紫锂辉手串",
    westernName: "Kunzite",
    resonance: ["Peace"],
    material: "Spodumene",
    description:
      "Translucent crystal blushing from lilac to soft pink, lit from within. A tender stone of serenity, kunzite dissolves anxiety and surrounds the wearer with a protective, peaceful warmth.",
    color: "#E1A6C4",
    price: 232,
    image: "/beads/kunzite.jpg",
    origin: "Nuristan, Afghanistan",
    age: "≈ 25 million years · Cenozoic pegmatite",
    energyAlignment: "Heart · peace and unguarded calm",
    diameterMm: 8,
  },
  {
    slug: "strawberry-quartz",
    name: "草莓晶手串",
    westernName: "Strawberry Quartz",
    resonance: ["Relationships"],
    material: "Quartz",
    description:
      "Rosy quartz freckled with red inclusions like seeds in summer fruit. A warm, sweet stone of affection, it is said to brighten the wearer's presence and draw kind company and easy connection near.",
    color: "#C65A6A",
    price: 178,
    image: "/beads/strawberry-quartz.jpg",
    origin: "Kazakhstan",
    age: "≈ 540 million years · Precambrian",
    energyAlignment: "Heart · warmth, charm and connection",
    diameterMm: 10,
  },
  {
    slug: "rhodochrosite",
    name: "红纹石手串",
    westernName: "Rhodochrosite",
    resonance: ["Relationships", "Emotion"],
    material: "Rhodochrosite",
    description:
      "Bands of rose and cream curling like a sunrise across the stone. The stone of the compassionate heart, rhodochrosite mends old hurt, steadies the emotions and opens the wearer to tender, generous love.",
    color: "#D98A9A",
    price: 196,
    image: "/beads/rhodochrosite.jpg",
    origin: "Capillitas, Argentina",
    age: "≈ 15 million years · Cenozoic hydrothermal",
    energyAlignment: "Heart · emotional healing and rapport",
    diameterMm: 10,
  },
  {
    slug: "purple-hair-super-seven",
    name: "紫发超七手串",
    westernName: "Purple Hair Super Seven",
    resonance: ["Relationships", "Study"],
    material: "Super Seven",
    description:
      "Seven minerals woven through a deep violet crystal threaded with fine rutile. A stone of presence and insight, it is worn to draw good company and to keep the studying mind clear, focused and inspired.",
    color: "#6E4A86",
    price: 256,
    image: "/beads/purple-hair-super-seven.jpg",
    origin: "Espírito Santo, Brazil",
    age: "≈ 500 million years · Precambrian",
    energyAlignment: "Third Eye · charisma and lucid focus",
    diameterMm: 10,
  },
  {
    slug: "white-phantom",
    name: "白幽晶手串",
    westernName: "White Phantom Quartz",
    resonance: ["Emotion"],
    material: "Quartz",
    description:
      "Clear quartz holding pale, ghostly phantoms of an earlier self within. A purifying, settling stone, it is said to clear emotional fog, dissolve lingering unease and return the wearer to a clean, quiet mind.",
    color: "#E6E8EA",
    price: 168,
    image: "/beads/white-phantom.jpg",
    origin: "Minas Gerais, Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Crown · clearing and emotional reset",
    diameterMm: 10,
  },
  {
    slug: "aquamarine",
    name: "海蓝宝手串",
    westernName: "Aquamarine",
    resonance: ["Emotion"],
    material: "Beryl",
    description:
      "Transparent crystal the colour of shallow sea, cool and clarifying. The stone of calm waters, aquamarine settles turbulent emotion, eases communication and carries the wearer's mood toward a serene, even tide.",
    color: "#A8D2DA",
    price: 244,
    image: "/beads/aquamarine.jpg",
    origin: "Minas Gerais, Brazil",
    age: "≈ 500 million years · Precambrian pegmatite",
    energyAlignment: "Throat · calm, clear feeling and speech",
    diameterMm: 8,
  },
  {
    slug: "purple-chalcedony",
    name: "紫玉髓手串",
    westernName: "Purple Chalcedony",
    resonance: ["Study"],
    material: "Chalcedony",
    description:
      "Smooth, even-toned violet stone with a soft inner glow. A quietly focusing stone, it is said to calm a busy mind, sharpen concentration and support the steady, patient work of learning.",
    color: "#8A6FA8",
    price: 162,
    image: "/beads/purple-chalcedony.jpg",
    origin: "Sulawesi, Indonesia",
    age: "≈ 20 million years · Cenozoic volcanic",
    energyAlignment: "Third Eye · concentration and calm study",
    diameterMm: 10,
  },
];

/** Fast slug → Bead lookup. */
export const BEAD_BY_SLUG: Record<string, Bead> = Object.fromEntries(
  BEADS.map((b) => [b.slug, b]),
);

export function getBead(slug: string): Bead | undefined {
  return BEAD_BY_SLUG[slug];
}

/** Sum the price of an ordered sequence of bead slugs. */
export function sequencePrice(slugs: string[]): number {
  return slugs.reduce((sum, slug) => sum + (BEAD_BY_SLUG[slug]?.price ?? 0), 0);
}

/** Sum the total diameter (mm) of a sequence of bead slugs. */
export function sequenceDiameterMm(slugs: string[]): number {
  return slugs.reduce((sum, slug) => sum + (BEAD_BY_SLUG[slug]?.diameterMm ?? 10), 0);
}

/** The eight resonance intentions, in chart order. */
export const RESONANCE_ORDER: ResonanceTag[] = [
  "Wealth",
  "Health",
  "Career",
  "Sleep",
  "Peace",
  "Relationships",
  "Emotion",
  "Study",
];

export const RESONANCE_COLORS: Record<ResonanceTag, string> = {
  Wealth: "#B8923A",
  Health: "#5A8A6A",
  Career: "#3D3D4A",
  Sleep: "#7B8BA8",
  Peace: "#9C2A24",
  Relationships: "#E8B4C0",
  Emotion: "#A8D2DA",
  Study: "#9B7BB8",
};

/** Approximate Mohs hardness by mineral family (language-neutral). */
export const MATERIAL_HARDNESS: Record<Material, string> = {
  Quartz: "7",
  Agate: "6.5–7",
  Chalcedony: "6.5–7",
  Obsidian: "5–5.5",
  Jade: "6–6.5",
  Feldspar: "6–6.5",
  Beryl: "7.5–8",
  Garnet: "6.5–7.5",
  Cinnabar: "2–2.5",
  Spodumene: "6.5–7",
  Prehnite: "6–6.5",
  Rhodochrosite: "3.5–4",
  "Super Seven": "7",
  "Lapis Lazuli": "5–5.5",
};

/** Materials present in the catalog, in a stable display order. */
export const MATERIAL_ORDER: Material[] = [
  "Quartz",
  "Agate",
  "Chalcedony",
  "Obsidian",
  "Jade",
  "Feldspar",
  "Beryl",
  "Garnet",
  "Cinnabar",
  "Spodumene",
  "Prehnite",
  "Rhodochrosite",
  "Super Seven",
  "Lapis Lazuli",
];
