import type { BraceletFormula } from "@/lib/types";
import { sequencePrice } from "@/lib/beads";

/**
 * THE CURATOR — atelier-composed signature bracelets.
 * Each is a deliberate arrangement keyed to a single intention.
 * Sequences are 14–16 beads to fill a standard bracelet.
 */
const rawCurated: Omit<BraceletFormula, "totalPrice">[] = [
  {
    id: "curated-abundance",
    name: "Abundance",
    description:
      "A composition for those calling prosperity inward — golden rutile threaded through clear quartz amplifies every intention, citrine keeps fortune in easy and generous motion, gold-sheen obsidian dissolves doubt at its volcanic root, and nephrite jade endures as the quiet keeper of what has already arrived. Worn when you are ready to receive.",
    beadSequence: [
      "rutilated-quartz",
      "citrine",
      "gold-sheen-obsidian",
      "nephrite-jade",
      "citrine",
      "rutilated-quartz",
      "tiger-eye",
      "citrine",
      "gold-sheen-obsidian",
      "nephrite-jade",
      "rutilated-quartz",
      "citrine",
      "gold-sheen-obsidian",
      "nephrite-jade",
      "citrine",
      "rutilated-quartz",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-serenity",
    name: "Serenity",
    description:
      "A quiet arrangement for stillness of mind — amethyst brings its violet calm like a slow, unhurried breath held just long enough. Clear quartz opens the field to receive it fully, amplifying stillness rather than sound. Smoky quartz, last to speak, draws the residue of the day through the wrist and releases it downward. For the evening return to oneself.",
    beadSequence: [
      "amethyst",
      "clear-quartz",
      "amethyst",
      "smoky-quartz",
      "clear-quartz",
      "amethyst",
      "clear-quartz",
      "amethyst",
      "smoky-quartz",
      "clear-quartz",
      "amethyst",
      "smoky-quartz",
      "clear-quartz",
      "amethyst",
      "smoky-quartz",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-vitality",
    name: "Vitality",
    description:
      "A grounding circle for restoration and steady strength — smoky quartz and black obsidian work in alternating pairs to anchor the wearer in the present moment, dissolving what exhausts and holding what sustains. Nephrite jade harmonizes the two forces, keeping the whole arrangement from tipping into heaviness. Citrine, placed at intervals, introduces warmth and forward motion into the stillness.",
    beadSequence: [
      "smoky-quartz",
      "black-obsidian",
      "nephrite-jade",
      "smoky-quartz",
      "black-obsidian",
      "nephrite-jade",
      "smoky-quartz",
      "citrine",
      "black-obsidian",
      "nephrite-jade",
      "smoky-quartz",
      "black-obsidian",
      "nephrite-jade",
      "smoky-quartz",
      "black-obsidian",
      "citrine",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-devotion",
    name: "Devotion",
    description:
      "For those opening the heart after a long closure — rose quartz makes up the majority of this arrangement, its blush energy amplified by repetition into something felt rather than merely worn. Amethyst creates a protective clarity within that openness, ensuring the heart's vulnerability is met with discernment rather than exposure. Clear quartz witnesses and holds the entire field steady. A quiet commitment to tenderness.",
    beadSequence: [
      "rose-quartz",
      "amethyst",
      "rose-quartz",
      "clear-quartz",
      "rose-quartz",
      "amethyst",
      "rose-quartz",
      "clear-quartz",
      "rose-quartz",
      "amethyst",
      "rose-quartz",
      "amethyst",
      "clear-quartz",
      "rose-quartz",
      "amethyst",
      "clear-quartz",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-midnight",
    name: "Midnight",
    description:
      "For those who move through the world as guardians — black obsidian forms the outer perimeter of this bracelet, its volcanic darkness absorbing what would otherwise reach the wearer. Black tourmalinated quartz works within, purifying the energetic field while keeping the mind sharp and present. Lapis lazuli, set at intervals, grants the ancient wisdom to discern what is genuinely threatening from what is merely unfamiliar. Worn with quiet authority.",
    beadSequence: [
      "black-obsidian",
      "black-hair-crystal",
      "black-obsidian",
      "lapis-lazuli",
      "black-obsidian",
      "black-hair-crystal",
      "black-obsidian",
      "black-hair-crystal",
      "black-obsidian",
      "lapis-lazuli",
      "black-obsidian",
      "black-hair-crystal",
      "black-obsidian",
      "lapis-lazuli",
      "black-obsidian",
      "black-hair-crystal",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-meridian",
    name: "The Meridian",
    description:
      "A composition for the seeker of truth — lapis lazuli, revered since antiquity as the stone of mind and conviction, aligns thought with held belief and sharpens the capacity for honest speech. Clear quartz holds the light between each stone, ensuring nothing is lost in translation. Where lapis can harden into certainty, amethyst softens the whole, reminding the wearer that truth, when fully arrived at, no longer needs to be defended. For those who think for themselves.",
    beadSequence: [
      "lapis-lazuli",
      "clear-quartz",
      "lapis-lazuli",
      "amethyst",
      "lapis-lazuli",
      "clear-quartz",
      "lapis-lazuli",
      "clear-quartz",
      "lapis-lazuli",
      "amethyst",
      "lapis-lazuli",
      "clear-quartz",
      "amethyst",
      "lapis-lazuli",
      "clear-quartz",
      "amethyst",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-momentum",
    name: "Momentum",
    description:
      "For the driven — this bracelet is built almost entirely of amplifiers. Rutilated quartz, threaded with golden filaments that move like arrested lightning, multiplies every intention the wearer brings. Tiger eye adds the decisiveness of action to the clarity of vision, the hunter's patience meeting the hawk's speed. Gold-sheen obsidian, placed at intervals, channels the accumulated charge — ambition without obsession, forward motion without loss of centre. Worn in moments of beginning.",
    beadSequence: [
      "rutilated-quartz",
      "tiger-eye",
      "rutilated-quartz",
      "rutilated-quartz",
      "tiger-eye",
      "rutilated-quartz",
      "gold-sheen-obsidian",
      "rutilated-quartz",
      "tiger-eye",
      "rutilated-quartz",
      "rutilated-quartz",
      "gold-sheen-obsidian",
      "rutilated-quartz",
      "tiger-eye",
      "rutilated-quartz",
      "gold-sheen-obsidian",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-sanctuary",
    name: "Sanctuary",
    description:
      "A wrist garden of inner equilibrium, composed for those who must give a great deal. Nephrite jade is the steadying axis — ancient, cooling, incorruptible — holding the arrangement in lasting balance. Rose quartz keeps the heart open to receive as well as give, preventing the quiet depletion that comes from generosity without replenishment. Smoky quartz transmutes what accumulates in the body, converting the residue of sustained contact with others into usable stillness. A piece for those who carry much.",
    beadSequence: [
      "nephrite-jade",
      "rose-quartz",
      "nephrite-jade",
      "smoky-quartz",
      "nephrite-jade",
      "rose-quartz",
      "nephrite-jade",
      "rose-quartz",
      "nephrite-jade",
      "smoky-quartz",
      "nephrite-jade",
      "rose-quartz",
      "smoky-quartz",
      "nephrite-jade",
      "rose-quartz",
      "smoky-quartz",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-ember",
    name: "Ember",
    description:
      "After depletion, before restoration — this bracelet is not a celebration but a recovery. Smoky quartz forms the majority of the sequence, its warm grey drawing off the residue of sustained effort layer by layer. Red agate, set at even intervals, reignites the vital flame — not dramatically, but steadily, the way embers return before they catch. Black obsidian seals the recovered energy in place, preventing it from dissipating again before it has had time to consolidate. Worn during convalescence.",
    beadSequence: [
      "smoky-quartz",
      "smoky-quartz",
      "red-agate",
      "smoky-quartz",
      "smoky-quartz",
      "red-agate",
      "black-obsidian",
      "smoky-quartz",
      "smoky-quartz",
      "red-agate",
      "smoky-quartz",
      "black-obsidian",
      "smoky-quartz",
      "red-agate",
      "smoky-quartz",
      "black-obsidian",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
  {
    id: "curated-nocturne",
    name: "Nocturne",
    description:
      "For the contemplative hour before sleep — amethyst, which makes up the majority of this bracelet, is the stone of the settling mind: neither fully awake nor surrendered to rest, but in the productive stillness between them. Lapis lazuli opens the inner eye to slow, unhurried perception that the pressured day rarely allows. Clear quartz holds the entire arrangement in an unhurried quiet, neither hastening rest nor preventing it. A bracelet for the last hour before the day is released.",
    beadSequence: [
      "amethyst",
      "amethyst",
      "lapis-lazuli",
      "amethyst",
      "amethyst",
      "lapis-lazuli",
      "amethyst",
      "clear-quartz",
      "amethyst",
      "lapis-lazuli",
      "amethyst",
      "clear-quartz",
      "amethyst",
      "lapis-lazuli",
      "amethyst",
      "clear-quartz",
    ],
    isCommunity: false,
    creatorName: "The Atelier",
  },
];

export const CURATED_BRACELETS: BraceletFormula[] = rawCurated.map((b) => ({
  ...b,
  totalPrice: sequencePrice(b.beadSequence),
}));

/**
 * THE COLLECTOR'S ATELIER — seeded community creations.
 * All sequences expanded to 14–16 beads.
 */
const rawCommunity: Omit<BraceletFormula, "totalPrice">[] = [
  {
    id: "community-sovereigns-rest",
    name: "The Sovereign's Rest",
    description:
      "Composed after a season of striving — protection at the wrists of ambition, with amethyst to remember stillness.",
    beadSequence: [
      "black-obsidian",
      "gold-sheen-obsidian",
      "amethyst",
      "black-obsidian",
      "gold-sheen-obsidian",
      "clear-quartz",
      "black-obsidian",
      "gold-sheen-obsidian",
      "amethyst",
      "black-obsidian",
      "clear-quartz",
      "gold-sheen-obsidian",
      "amethyst",
      "black-obsidian",
    ],
    isCommunity: true,
    creatorName: "Élise V.",
  },
  {
    id: "community-goldenhour",
    name: "Golden Hour",
    description:
      "A bright, optimistic circle worn from desk to dinner — citrine and rutile for momentum, jade to keep it graceful.",
    beadSequence: [
      "citrine",
      "rutilated-quartz",
      "citrine",
      "nephrite-jade",
      "rutilated-quartz",
      "citrine",
      "tiger-eye",
      "citrine",
      "rutilated-quartz",
      "nephrite-jade",
      "citrine",
      "rutilated-quartz",
      "citrine",
      "tiger-eye",
      "nephrite-jade",
    ],
    isCommunity: true,
    creatorName: "Marcus T.",
  },
  {
    id: "community-still-water",
    name: "Still Water",
    description:
      "Designed for the overstimulated mind — a near-monochrome arrangement of quartz and amethyst, like a held breath.",
    beadSequence: [
      "clear-quartz",
      "amethyst",
      "clear-quartz",
      "smoky-quartz",
      "amethyst",
      "clear-quartz",
      "amethyst",
      "clear-quartz",
      "smoky-quartz",
      "clear-quartz",
      "amethyst",
      "smoky-quartz",
      "clear-quartz",
      "amethyst",
      "clear-quartz",
    ],
    isCommunity: true,
    creatorName: "Priya N.",
  },
  {
    id: "community-the-cartographer",
    name: "The Cartographer",
    description:
      "For a friend setting out on something uncertain — grounding obsidian paired with amplifying rutile, to find and hold the way.",
    beadSequence: [
      "black-obsidian",
      "rutilated-quartz",
      "nephrite-jade",
      "rutilated-quartz",
      "black-obsidian",
      "gold-sheen-obsidian",
      "black-obsidian",
      "rutilated-quartz",
      "nephrite-jade",
      "black-obsidian",
      "rutilated-quartz",
      "gold-sheen-obsidian",
      "nephrite-jade",
      "black-obsidian",
    ],
    isCommunity: true,
    creatorName: "Johan R.",
  },
];

export const COMMUNITY_BRACELETS: BraceletFormula[] = rawCommunity.map((b) => ({
  ...b,
  totalPrice: sequencePrice(b.beadSequence),
}));

/** Everything that should live in the database. */
export const ALL_BRACELETS: BraceletFormula[] = [
  ...CURATED_BRACELETS,
  ...COMMUNITY_BRACELETS,
];
